// Parliament-Sourced Woman Representatives Data
import type { CoalitionType } from './kenya-data';
export interface ParliamentWomanRep { id: string; fullName: string; officialTitle: string; party: string; coalition: CoalitionType; jurisdiction: string; countyName: string; countyCode: number; status: 'Elected'; profileUrl: string; rawName: string; source: 'Parliament of Kenya (parliament.go.ke)'; }

export function getParliamentWomanRepForCounty(countyName: string): ParliamentWomanRep | null {
  switch (countyName) {
    case "Mombasa": return { id: "wrep-parliament-mombasa", fullName: 'Mohammed Zamzam Chimba', officialTitle: "Woman Rep, Mombasa County", party: 'ODM', coalition: 'Azimio', jurisdiction: "Mombasa County", countyName: "Mombasa", countyCode: 1, status: "Elected", profileUrl: 'https://www.parliament.go.ke/the-national-assembly/hon-mohammed-zamzam-chimba', rawName: 'HON. MOHAMMED ZAMZAM CHIMBA', source: "Parliament of Kenya (parliament.go.ke)" };
    case "Kwale": return { id: "wrep-parliament-kwale", fullName: 'Masito, Fatuma Hamisi', officialTitle: "Woman Rep, Kwale County", party: 'ODM', coalition: 'Azimio', jurisdiction: "Kwale County", countyName: "Kwale", countyCode: 2, status: "Elected", profileUrl: 'https://www.parliament.go.ke/the-national-assembly/hon-masito-fatuma-hamisi', rawName: 'HON. MASITO, FATUMA HAMISI', source: "Parliament of Kenya (parliament.go.ke)" };
    case "Kilifi": return { id: "wrep-parliament-kilifi", fullName: 'Mwanyanje Gertrude Mbeyu', officialTitle: "Woman Rep, Kilifi County", party: 'ODM', coalition: 'Azimio', jurisdiction: "Kilifi County", countyName: "Kilifi", countyCode: 3, status: "Elected", profileUrl: 'https://www.parliament.go.ke/the-national-assembly/hon-mwanyanje-gertrude-mbeyu-cbs', rawName: 'HON. MWANYANJE GERTRUDE MBEYU, CBS', source: "Parliament of Kenya (parliament.go.ke)" };
    case "Tana River": return { id: "wrep-parliament-tana-river", fullName: 'Abdullahi Amina Dika', officialTitle: "Woman Rep, Tana River County", party: 'KANU', coalition: 'Kenya Kwanza', jurisdiction: "Tana River County", countyName: "Tana River", countyCode: 4, status: "Elected", profileUrl: 'https://www.parliament.go.ke/the-national-assembly/hon-abdullahi-amina-dika', rawName: 'HON. ABDULLAHI AMINA DIKA', source: "Parliament of Kenya (parliament.go.ke)" };
    case "Lamu": return { id: "wrep-parliament-lamu", fullName: 'Marubu Muthoni Monicah', officialTitle: "Woman Rep, Lamu County", party: 'IND', coalition: 'Independent', jurisdiction: "Lamu County", countyName: "Lamu", countyCode: 5, status: "Elected", profileUrl: 'https://www.parliament.go.ke/the-national-assembly/hon-marubu-muthoni-monicah', rawName: 'HON. MARUBU MUTHONI MONICAH', source: "Parliament of Kenya (parliament.go.ke)" };
    case "Taita Taveta": return { id: "wrep-parliament-taita-taveta", fullName: 'Mizighi Lydia Haika', officialTitle: "Woman Rep, Taita Taveta County", party: 'UDA', coalition: 'Kenya Kwanza', jurisdiction: "Taita Taveta County", countyName: "Taita Taveta", countyCode: 6, status: "Elected", profileUrl: 'https://www.parliament.go.ke/the-national-assembly/hon-mizighi-lydia-haika', rawName: 'HON. MIZIGHI LYDIA HAIKA', source: "Parliament of Kenya (parliament.go.ke)" };
    case "Garissa": return { id: "wrep-parliament-garissa", fullName: 'Kuno, Amina Udgoon Siyad', officialTitle: "Woman Rep, Garissa County", party: 'JP', coalition: 'Kenya Kwanza', jurisdiction: "Garissa County", countyName: "Garissa", countyCode: 7, status: "Elected", profileUrl: 'https://www.parliament.go.ke/the-national-assembly/hon-kuno-amina-udgoon-siyad', rawName: 'HON. KUNO, AMINA UDGOON SIYAD', source: "Parliament of Kenya (parliament.go.ke)" };
    case "Wajir": return { id: "wrep-parliament-wajir", fullName: 'Jehow Fatuma Abdi', officialTitle: "Woman Rep, Wajir County", party: 'ODM', coalition: 'Azimio', jurisdiction: "Wajir County", countyName: "Wajir", countyCode: 8, status: "Elected", profileUrl: 'https://www.parliament.go.ke/the-national-assembly/hon-jehow-fatuma-abdi', rawName: 'HON. JEHOW FATUMA ABDI', source: "Parliament of Kenya (parliament.go.ke)" };
    case "Mandera": return { id: "wrep-parliament-mandera", fullName: 'Sheikh Umul Ker Kassim', officialTitle: "Woman Rep, Mandera County", party: 'UDM', coalition: 'Kenya Kwanza', jurisdiction: "Mandera County", countyName: "Mandera", countyCode: 9, status: "Elected", profileUrl: 'https://www.parliament.go.ke/the-national-assembly/hon-sheikh-umul-ker-kassim', rawName: 'HON. SHEIKH UMUL KER KASSIM', source: "Parliament of Kenya (parliament.go.ke)" };
    case "Marsabit": return { id: "wrep-parliament-marsabit", fullName: 'Waqo Naomi Jillo', officialTitle: "Woman Rep, Marsabit County", party: 'UDA', coalition: 'Kenya Kwanza', jurisdiction: "Marsabit County", countyName: "Marsabit", countyCode: 10, status: "Elected", profileUrl: 'https://www.parliament.go.ke/the-national-assembly/hon-waqo-naomi-jillo', rawName: 'HON. WAQO NAOMI JILLO', source: "Parliament of Kenya (parliament.go.ke)" };
    case "Isiolo": return { id: "wrep-parliament-isiolo", fullName: 'Bonaya Mumina Gollo', officialTitle: "Woman Rep, Isiolo County", party: 'JP', coalition: 'Kenya Kwanza', jurisdiction: "Isiolo County", countyName: "Isiolo", countyCode: 11, status: "Elected", profileUrl: 'https://www.parliament.go.ke/the-national-assembly/hon-bonaya-mumina-gollo', rawName: 'HON. BONAYA MUMINA GOLLO', source: "Parliament of Kenya (parliament.go.ke)" };
    case "Meru": return { id: "wrep-parliament-meru", fullName: 'Kailemia Elizabeth Karambu', officialTitle: "Woman Rep, Meru County", party: 'UDA', coalition: 'Kenya Kwanza', jurisdiction: "Meru County", countyName: "Meru", countyCode: 12, status: "Elected", profileUrl: 'https://www.parliament.go.ke/the-national-assembly/hon-kailemia-elizabeth-karambu', rawName: 'HON. KAILEMIA ELIZABETH KARAMBU', source: "Parliament of Kenya (parliament.go.ke)" };
    case "Tharaka Nithi": return { id: "wrep-parliament-tharaka-nithi", fullName: 'Nduyo Susan Ngugi', officialTitle: "Woman Rep, Tharaka Nithi County", party: 'TSP', coalition: 'Kenya Kwanza', jurisdiction: "Tharaka Nithi County", countyName: "Tharaka Nithi", countyCode: 13, status: "Elected", profileUrl: 'https://www.parliament.go.ke/the-national-assembly/hon-nduyo-susan-ngugi', rawName: 'HON. NDUYO SUSAN NGUGI', source: "Parliament of Kenya (parliament.go.ke)" };
    case "Embu": return { id: "wrep-parliament-embu", fullName: 'Njeru Pamela Njoki', officialTitle: "Woman Rep, Embu County", party: 'UDA', coalition: 'Kenya Kwanza', jurisdiction: "Embu County", countyName: "Embu", countyCode: 14, status: "Elected", profileUrl: 'https://www.parliament.go.ke/the-national-assembly/hon-njeru-pamela-njoki', rawName: 'HON. NJERU PAMELA NJOKI', source: "Parliament of Kenya (parliament.go.ke)" };
    case "Kitui": return { id: "wrep-parliament-kitui", fullName: 'Kasalu, Irene Muthoni', officialTitle: "Woman Rep, Kitui County", party: 'WDM', coalition: 'Kenya Kwanza', jurisdiction: "Kitui County", countyName: "Kitui", countyCode: 15, status: "Elected", profileUrl: 'https://www.parliament.go.ke/the-national-assembly/hon-kasalu-irene-muthoni', rawName: 'HON. KASALU, IRENE MUTHONI', source: "Parliament of Kenya (parliament.go.ke)" };
    case "Machakos": return { id: "wrep-parliament-machakos", fullName: 'Kamene', officialTitle: "Woman Rep, Machakos County", party: 'WDM', coalition: 'Kenya Kwanza', jurisdiction: "Machakos County", countyName: "Machakos", countyCode: 16, status: "Elected", profileUrl: 'https://www.parliament.go.ke/the-national-assembly/hon-kamene-joyce', rawName: 'HON. KAMENE, JOYCE', source: "Parliament of Kenya (parliament.go.ke)" };
    case "Makueni": return { id: "wrep-parliament-makueni", fullName: 'Kiamba Suzanne Ndunge', officialTitle: "Woman Rep, Makueni County", party: 'WDM', coalition: 'Kenya Kwanza', jurisdiction: "Makueni County", countyName: "Makueni", countyCode: 17, status: "Elected", profileUrl: 'https://www.parliament.go.ke/the-national-assembly/hon-kiamba-suzanne-ndunge', rawName: 'HON. KIAMBA SUZANNE NDUNGE', source: "Parliament of Kenya (parliament.go.ke)" };
    case "Nyandarua": return { id: "wrep-parliament-nyandarua", fullName: 'Gitau Faith Wairimu', officialTitle: "Woman Rep, Nyandarua County", party: 'UDA', coalition: 'Kenya Kwanza', jurisdiction: "Nyandarua County", countyName: "Nyandarua", countyCode: 18, status: "Elected", profileUrl: 'https://www.parliament.go.ke/the-national-assembly/hon-gitau-faith-wairimu-0', rawName: 'HON. GITAU FAITH WAIRIMU', source: "Parliament of Kenya (parliament.go.ke)" };
    case "Nyeri": return { id: "wrep-parliament-nyeri", fullName: 'Wachira, Rahab Mukami', officialTitle: "Woman Rep, Nyeri County", party: 'UDA', coalition: 'Kenya Kwanza', jurisdiction: "Nyeri County", countyName: "Nyeri", countyCode: 19, status: "Elected", profileUrl: 'https://www.parliament.go.ke/the-national-assembly/hon-wachira-rahab-mukami-0', rawName: 'HON. WACHIRA,  RAHAB MUKAMI', source: "Parliament of Kenya (parliament.go.ke)" };
    case "Kirinyaga": return { id: "wrep-parliament-kirinyaga", fullName: 'Maina Jane Njeri', officialTitle: "Woman Rep, Kirinyaga County", party: 'UDA', coalition: 'Kenya Kwanza', jurisdiction: "Kirinyaga County", countyName: "Kirinyaga", countyCode: 20, status: "Elected", profileUrl: 'https://www.parliament.go.ke/the-national-assembly/hon-maina-jane-njeri', rawName: 'HON. MAINA JANE NJERI', source: "Parliament of Kenya (parliament.go.ke)" };
    case "Murang'a": return { id: "wrep-parliament-murang-a", fullName: 'Maina, Betty Njeri', officialTitle: "Woman Rep, Murang'a County", party: 'UDA', coalition: 'Kenya Kwanza', jurisdiction: "Murang'a County", countyName: "Murang'a", countyCode: 21, status: "Elected", profileUrl: 'https://www.parliament.go.ke/the-national-assembly/hon-maina-betty-njeri', rawName: 'HON. MAINA, BETTY NJERI', source: "Parliament of Kenya (parliament.go.ke)" };
    case "Kiambu": return { id: "wrep-parliament-kiambu", fullName: 'Muratha Anne Wanjiku Mugo', officialTitle: "Woman Rep, Kiambu County", party: 'UDA', coalition: 'Kenya Kwanza', jurisdiction: "Kiambu County", countyName: "Kiambu", countyCode: 22, status: "Elected", profileUrl: 'https://www.parliament.go.ke/the-national-assembly/hon-muratha-anne-wanjiku-mugo', rawName: 'HON. MURATHA ANNE WANJIKU MUGO', source: "Parliament of Kenya (parliament.go.ke)" };
    case "Turkana": return { id: "wrep-parliament-turkana", fullName: 'Ngitit, Cecilia Asinyen', officialTitle: "Woman Rep, Turkana County", party: 'UDA', coalition: 'Kenya Kwanza', jurisdiction: "Turkana County", countyName: "Turkana", countyCode: 23, status: "Elected", profileUrl: 'https://www.parliament.go.ke/the-national-assembly/hon-ngitit-cecilia-asinyen', rawName: 'HON. NGITIT, CECILIA ASINYEN', source: "Parliament of Kenya (parliament.go.ke)" };
    case "West Pokot": return { id: "wrep-parliament-west-pokot", fullName: 'Kasiwai Rael Kasiwai', officialTitle: "Woman Rep, West Pokot County", party: 'KUP', coalition: 'Kenya Kwanza', jurisdiction: "West Pokot County", countyName: "West Pokot", countyCode: 24, status: "Elected", profileUrl: 'https://www.parliament.go.ke/the-national-assembly/hon-kasiwai-rael-kasiwai', rawName: 'HON. KASIWAI RAEL KASIWAI', source: "Parliament of Kenya (parliament.go.ke)" };
    case "Samburu": return { id: "wrep-parliament-samburu", fullName: 'Lenguris Pauline', officialTitle: "Woman Rep, Samburu County", party: 'UDA', coalition: 'Kenya Kwanza', jurisdiction: "Samburu County", countyName: "Samburu", countyCode: 25, status: "Elected", profileUrl: 'https://www.parliament.go.ke/the-national-assembly/hon-lenguris-pauline', rawName: 'HON. LENGURIS PAULINE', source: "Parliament of Kenya (parliament.go.ke)" };
    case "Trans-Nzoia": return { id: "wrep-parliament-trans-nzoia", fullName: 'Siyoi Lillian Chebet', officialTitle: "Woman Rep, Trans-Nzoia County", party: 'UDA', coalition: 'Kenya Kwanza', jurisdiction: "Trans-Nzoia County", countyName: "Trans-Nzoia", countyCode: 26, status: "Elected", profileUrl: 'https://www.parliament.go.ke/the-national-assembly/hon-siyoi-lillian-chebet', rawName: 'HON. SIYOI LILLIAN CHEBET', source: "Parliament of Kenya (parliament.go.ke)" };
    case "Uasin Gishu": return { id: "wrep-parliament-uasin-gishu", fullName: 'Boss Gladys Jepkosgei', officialTitle: "Woman Rep, Uasin Gishu County", party: 'UDA', coalition: 'Kenya Kwanza', jurisdiction: "Uasin Gishu County", countyName: "Uasin Gishu", countyCode: 27, status: "Elected", profileUrl: 'https://www.parliament.go.ke/the-national-assembly/hon-boss-gladys-jepkosgei', rawName: 'HON. BOSS GLADYS JEPKOSGEI', source: "Parliament of Kenya (parliament.go.ke)" };
    case "Elgeyo-Marakwet": return { id: "wrep-parliament-elgeyo-marakwet", fullName: 'Ng’Elechei Caroline Jeptoo', officialTitle: "Woman Rep, Elgeyo-Marakwet County", party: 'IND', coalition: 'Independent', jurisdiction: "Elgeyo-Marakwet County", countyName: "Elgeyo-Marakwet", countyCode: 28, status: "Elected", profileUrl: 'https://www.parliament.go.ke/the-national-assembly/hon-ngelechei-caroline-jeptoo', rawName: 'HON. NG’ELECHEI CAROLINE JEPTOO', source: "Parliament of Kenya (parliament.go.ke)" };
    case "Nandi": return { id: "wrep-parliament-nandi", fullName: 'Muge Cynthia Jepkosgei', officialTitle: "Woman Rep, Nandi County", party: 'UDA', coalition: 'Kenya Kwanza', jurisdiction: "Nandi County", countyName: "Nandi", countyCode: 29, status: "Elected", profileUrl: 'https://www.parliament.go.ke/the-national-assembly/hon-muge-cynthia-jepkosgei', rawName: 'HON. MUGE CYNTHIA JEPKOSGEI', source: "Parliament of Kenya (parliament.go.ke)" };
    case "Baringo": return { id: "wrep-parliament-baringo", fullName: 'Sergon, Jematiah Flowrence', officialTitle: "Woman Rep, Baringo County", party: 'UDA', coalition: 'Kenya Kwanza', jurisdiction: "Baringo County", countyName: "Baringo", countyCode: 30, status: "Elected", profileUrl: 'https://www.parliament.go.ke/the-national-assembly/hon-sergon-jematiah-flowrence', rawName: 'HON. SERGON, JEMATIAH FLOWRENCE', source: "Parliament of Kenya (parliament.go.ke)" };
    case "Laikipia": return { id: "wrep-parliament-laikipia", fullName: 'Kagiri Jane Wangechi', officialTitle: "Woman Rep, Laikipia County", party: 'UDA', coalition: 'Kenya Kwanza', jurisdiction: "Laikipia County", countyName: "Laikipia", countyCode: 31, status: "Elected", profileUrl: 'https://www.parliament.go.ke/the-national-assembly/hon-kagiri-jane-wangechi', rawName: 'HON. KAGIRI JANE WANGECHI', source: "Parliament of Kenya (parliament.go.ke)" };
    case "Nakuru": return { id: "wrep-parliament-nakuru", fullName: 'Chelule, Liza Chepkorir', officialTitle: "Woman Rep, Nakuru County", party: 'UDA', coalition: 'Kenya Kwanza', jurisdiction: "Nakuru County", countyName: "Nakuru", countyCode: 32, status: "Elected", profileUrl: 'https://www.parliament.go.ke/the-national-assembly/hon-chelule-liza-chepkorir', rawName: 'HON. CHELULE, LIZA CHEPKORIR', source: "Parliament of Kenya (parliament.go.ke)" };
    case "Narok": return { id: "wrep-parliament-narok", fullName: 'Tonkei Rebecca Noonaishi', officialTitle: "Woman Rep, Narok County", party: 'UDA', coalition: 'Kenya Kwanza', jurisdiction: "Narok County", countyName: "Narok", countyCode: 33, status: "Elected", profileUrl: 'https://www.parliament.go.ke/the-national-assembly/hon-tonkei-rebecca-noonaishi', rawName: 'HON. TONKEI REBECCA NOONAISHI', source: "Parliament of Kenya (parliament.go.ke)" };
    case "Kajiado": return { id: "wrep-parliament-kajiado", fullName: 'Sankaire Leah Sopiato', officialTitle: "Woman Rep, Kajiado County", party: 'UDA', coalition: 'Kenya Kwanza', jurisdiction: "Kajiado County", countyName: "Kajiado", countyCode: 34, status: "Elected", profileUrl: 'https://www.parliament.go.ke/the-national-assembly/hon-sankaire-leah-sopiato', rawName: 'HON. SANKAIRE LEAH SOPIATO', source: "Parliament of Kenya (parliament.go.ke)" };
    case "Kericho": return { id: "wrep-parliament-kericho", fullName: 'Kemei, Beatrice Chepngeno', officialTitle: "Woman Rep, Kericho County", party: 'UDA', coalition: 'Kenya Kwanza', jurisdiction: "Kericho County", countyName: "Kericho", countyCode: 35, status: "Elected", profileUrl: 'https://www.parliament.go.ke/the-national-assembly/hon-kemei-beatrice-chepngeno', rawName: 'HON. KEMEI, BEATRICE CHEPNGENO', source: "Parliament of Kenya (parliament.go.ke)" };
    case "Bomet": return { id: "wrep-parliament-bomet", fullName: 'Chepkorir', officialTitle: "Woman Rep, Bomet County", party: 'UDA', coalition: 'Kenya Kwanza', jurisdiction: "Bomet County", countyName: "Bomet", countyCode: 36, status: "Elected", profileUrl: 'https://www.parliament.go.ke/the-national-assembly/hon-chepkorir-linet', rawName: 'HON. CHEPKORIR, LINET', source: "Parliament of Kenya (parliament.go.ke)" };
    case "Kakamega": return { id: "wrep-parliament-kakamega", fullName: 'Muhanda Elsie Busihile', officialTitle: "Woman Rep, Kakamega County", party: 'ODM', coalition: 'Azimio', jurisdiction: "Kakamega County", countyName: "Kakamega", countyCode: 37, status: "Elected", profileUrl: 'https://www.parliament.go.ke/the-national-assembly/hon-muhanda-elsie-busihile', rawName: 'HON. MUHANDA ELSIE BUSIHILE', source: "Parliament of Kenya (parliament.go.ke)" };
    case "Vihiga": return { id: "wrep-parliament-vihiga", fullName: 'Adagala, Beatrice Kahai', officialTitle: "Woman Rep, Vihiga County", party: 'ANC', coalition: 'Kenya Kwanza', jurisdiction: "Vihiga County", countyName: "Vihiga", countyCode: 38, status: "Elected", profileUrl: 'https://www.parliament.go.ke/the-national-assembly/hon-adagala-beatrice-kahai', rawName: 'HON. ADAGALA, BEATRICE KAHAI', source: "Parliament of Kenya (parliament.go.ke)" };
    case "Bungoma": return { id: "wrep-parliament-bungoma", fullName: 'Wambilianga Catherine Nanjala', officialTitle: "Woman Rep, Bungoma County", party: 'FORD-K', coalition: 'Kenya Kwanza', jurisdiction: "Bungoma County", countyName: "Bungoma", countyCode: 39, status: "Elected", profileUrl: 'https://www.parliament.go.ke/the-national-assembly/hon-wambilianga-catherine-nanjala-0', rawName: 'HON. WAMBILIANGA CATHERINE NANJALA', source: "Parliament of Kenya (parliament.go.ke)" };
    case "Busia": return { id: "wrep-parliament-busia", fullName: 'Omanyo, Catherine Nakhabi', officialTitle: "Woman Rep, Busia County", party: 'ODM', coalition: 'Azimio', jurisdiction: "Busia County", countyName: "Busia", countyCode: 40, status: "Elected", profileUrl: 'https://www.parliament.go.ke/the-national-assembly/hon-omanyo-catherine-nakhabi', rawName: 'HON. OMANYO, CATHERINE NAKHABI', source: "Parliament of Kenya (parliament.go.ke)" };
    case "Siaya": return { id: "wrep-parliament-siaya", fullName: 'Ombaka Oduor Christine', officialTitle: "Woman Rep, Siaya County", party: 'ODM', coalition: 'Azimio', jurisdiction: "Siaya County", countyName: "Siaya", countyCode: 41, status: "Elected", profileUrl: 'https://www.parliament.go.ke/the-national-assembly/hon-ombaka-oduor-christine-cbs', rawName: 'HON. OMBAKA ODUOR CHRISTINE, CBS', source: "Parliament of Kenya (parliament.go.ke)" };
    case "Kisumu": return { id: "wrep-parliament-kisumu", fullName: 'Busia Ruth Adhiambo Odinga', officialTitle: "Woman Rep, Kisumu County", party: 'ODM', coalition: 'Azimio', jurisdiction: "Kisumu County", countyName: "Kisumu", countyCode: 42, status: "Elected", profileUrl: 'https://www.parliament.go.ke/the-national-assembly/hon-busia-ruth-adhiambo-odinga', rawName: 'HON. BUSIA RUTH ADHIAMBO ODINGA', source: "Parliament of Kenya (parliament.go.ke)" };
    case "Homa Bay": return { id: "wrep-parliament-homa-bay", fullName: 'Osogo Joyce Atieno Bensuda', officialTitle: "Woman Rep, Homa Bay County", party: 'ODM', coalition: 'Azimio', jurisdiction: "Homa Bay County", countyName: "Homa Bay", countyCode: 43, status: "Elected", profileUrl: 'https://www.parliament.go.ke/the-national-assembly/hon-osogo-joyce-atieno-bensuda', rawName: 'HON. OSOGO JOYCE ATIENO BENSUDA', source: "Parliament of Kenya (parliament.go.ke)" };
    case "Migori": return { id: "wrep-parliament-migori", fullName: 'Mohammed Fatuma Zainab', officialTitle: "Woman Rep, Migori County", party: 'IND', coalition: 'Independent', jurisdiction: "Migori County", countyName: "Migori", countyCode: 44, status: "Elected", profileUrl: 'https://www.parliament.go.ke/the-national-assembly/hon-mohammed-fatuma-zainab', rawName: 'HON. MOHAMMED FATUMA ZAINAB', source: "Parliament of Kenya (parliament.go.ke)" };
    case "Kisii": return { id: "wrep-parliament-kisii", fullName: 'Aburi Donya Dorice', officialTitle: "Woman Rep, Kisii County", party: 'WDM', coalition: 'Kenya Kwanza', jurisdiction: "Kisii County", countyName: "Kisii", countyCode: 45, status: "Elected", profileUrl: 'https://www.parliament.go.ke/the-national-assembly/hon-aburi-donya-dorice', rawName: 'HON. ABURI DONYA DORICE', source: "Parliament of Kenya (parliament.go.ke)" };
    case "Nyamira": return { id: "wrep-parliament-nyamira", fullName: 'Mongina Jerusha Momanyi', officialTitle: "Woman Rep, Nyamira County", party: 'JP', coalition: 'Kenya Kwanza', jurisdiction: "Nyamira County", countyName: "Nyamira", countyCode: 46, status: "Elected", profileUrl: 'https://www.parliament.go.ke/the-national-assembly/hon-mongina-jerusha-momanyi', rawName: 'HON. MONGINA JERUSHA MOMANYI', source: "Parliament of Kenya (parliament.go.ke)" };
    case "Nairobi City": return { id: "wrep-parliament-nairobi-city", fullName: 'Passaris Esther Muthoni', officialTitle: "Woman Rep, Nairobi City County", party: 'ODM', coalition: 'Azimio', jurisdiction: "Nairobi City County", countyName: "Nairobi City", countyCode: 47, status: "Elected", profileUrl: 'https://www.parliament.go.ke/the-national-assembly/hon-passaris-esther-muthoni', rawName: 'HON. PASSARIS ESTHER MUTHONI', source: "Parliament of Kenya (parliament.go.ke)" };
    default: return null;
  }
}
export const PARLIAMENT_WOMEN_REPS_TOTAL = 47;