#!/usr/bin/env python3
"""Emit kenya-parliament-mps.ts from the cleaned MP JSON."""
import json, re, sys
from pathlib import Path
from collections import defaultdict

INPUT = Path("/home/z/my-project/upload/mps/mps_parliament_ke_clean.json")
OUTPUT = Path("/home/z/my-project/src/lib/kenya-parliament-mps.ts")

OFFICIAL_COUNTY_NAMES = [
    "Mombasa", "Kwale", "Kilifi", "Tana River", "Lamu", "Taita Taveta",
    "Garissa", "Wajir", "Mandera", "Marsabit", "Isiolo", "Meru",
    "Tharaka Nithi", "Embu", "Kitui", "Machakos", "Makueni", "Nyandarua",
    "Nyeri", "Kirinyaga", "Murang'a", "Kiambu", "Turkana", "West Pokot",
    "Samburu", "Trans-Nzoia", "Uasin Gishu", "Elgeyo-Marakwet", "Nandi",
    "Baringo", "Laikipia", "Nakuru", "Narok", "Kajiado", "Kericho", "Bomet",
    "Kakamega", "Vihiga", "Bungoma", "Busia", "Siaya", "Kisumu", "Homa Bay",
    "Migori", "Kisii", "Nyamira", "Nairobi City",
]
COUNTY_CODES = {n: i+1 for i, n in enumerate(OFFICIAL_COUNTY_NAMES)}

COUNTY_NORMALIZATION = {}
for name in OFFICIAL_COUNTY_NAMES:
    COUNTY_NORMALIZATION[name.upper()] = name
    COUNTY_NORMALIZATION[name.upper().replace("'", "").replace("-", " ")] = name
    COUNTY_NORMALIZATION[name.upper().replace("-", " ")] = name
    COUNTY_NORMALIZATION[name.upper().replace(" ", "-")] = name
COUNTY_NORMALIZATION.update({
    "MURANGA": "Murang'a", "MURANGÁ": "Murang'a", "MURANG'A": "Murang'a", "MURANG’A": "Murang'a",
    "TRANS NZOIA": "Trans-Nzoia", "ELGEYO MARAKWET": "Elgeyo-Marakwet",
    "ELGEYO - MARAKWET": "Elgeyo-Marakwet", "THARAKA NITHI": "Tharaka Nithi",
    "THARAKA-NITHI": "Tharaka Nithi", "THARAKA - NITHI": "Tharaka Nithi",
    "NAIROBI": "Nairobi City", "HOMABAY": "Homa Bay", "ISIOLO NORTH": "Isiolo",
    "NYAMIRA COUNTY": "Nyamira", "POKOT": "West Pokot", "NOMINATED": None,
    "MWINGI": None,
})

KENYA_KWANZA = {"UDA","JP","WDM","ANC","FORD-K","FORD-A","KANU","PAA","KUP","UDM","CCM","NAP-K","MDG","DCP","MCCP","UPIA","TSP"}
AZIMIO = {"ODM","JUBILEE","WIPER","DAP-K","UPA","NARC","NARC-K","NOPEU","GDDP"}
IND = {"IND","IND."}

KNOWN_ACRONYMS = {"CBS","EGH","CS","CGS","EBS","OGW","HSC","MBS","MP","GH"}

def normalize_county(raw):
    if not raw: return None
    return COUNTY_NORMALIZATION.get(raw.upper().strip())

def normalize_party(raw):
    if not raw: return "", "Other"
    p = raw.upper().strip()
    p = {"FORD - K":"FORD-K","FORD - A":"FORD-A","ODM | AZIMIO LA UMOJA ONE KENYA COALITION":"ODM","IND.":"IND"}.get(p, p)
    if p in IND: return "IND", "Independent"
    if p in KENYA_KWANZA: return p, "Kenya Kwanza"
    if p in AZIMIO: return p, "Azimio"
    return p, "Other"

def title_case_name(raw_name):
    if not raw_name: return ""
    name = re.sub(r'\s+', ' ', raw_name).strip()
    def fix_paren(m):
        inner = m.group(1)
        if " " not in inner:
            title = inner.title()
            if not title.endswith("."): title += "."
            return f"({title})"
        return m.group(0)
    name = re.sub(r'\(([^)]+)\)', fix_paren, name)
    words = name.split(' ')
    titled = []
    for w in words:
        if not w: continue
        if w in KNOWN_ACRONYMS: titled.append(w); continue
        word_titled = w.title()
        word_titled = re.sub(r"'([A-Z])", lambda m: "'" + m.group(1).lower(), word_titled)
        titled.append(word_titled)
    return ' '.join(titled)

def make_mp_id(county, constituency):
    def slugify(s): return re.sub(r'[^a-z0-9]+', '-', s.lower()).strip('-')
    return f"mp-parliament-{slugify(county)}-{slugify(constituency or 'unknown')}"

with open(INPUT) as f:
    data = json.load(f)
mps = data["mps"]

mps_by_county = defaultdict(list)
for mp in mps:
    county = normalize_county(mp["county"])
    if county is None: continue
    name = title_case_name(mp["name"])
    if not name: continue
    party, coalition = normalize_party(mp["party"])
    constituency = mp["constituency"].title() if mp["constituency"] else ""
    raw_status = mp["status"].upper().strip() if mp["status"] else ""
    VALID = {"ELECTED","NOMINATED","ELECT","WOMAN REP","EX-OFFICIO"}
    if raw_status in VALID:
        status = "Elected" if raw_status == "ELECT" else raw_status.title()
    elif raw_status in KENYA_KWANZA or raw_status in AZIMIO or raw_status in IND:
        if not party and raw_status: party, coalition = normalize_party(raw_status)
        status = "Elected"
    else: status = "Elected"
    mp_id = make_mp_id(county, constituency)
    mps_by_county[county].append({"id":mp_id,"name":name,"party":party,"coalition":coalition,
        "constituency":constituency,"county":county,"code":COUNTY_CODES.get(county,0),
        "status":status,"profile_url":mp.get("profile_url",""),"raw_name":mp.get("raw_name",name)})

lines = ["// Parliament-Sourced MP Data — verified from parliament.go.ke",
    "// Generated by scripts/emit_parliament_mps_ts.py",
    "import type { CoalitionType } from './kenya-data';",
    "export interface ParliamentMP { id: string; fullName: string; officialTitle: string; party: string; coalition: CoalitionType; jurisdiction: string; countyName: string; countyCode: number; status: 'Elected' | 'Nominated'; profileUrl: string; rawName: string; source: 'Parliament of Kenya (parliament.go.ke)'; }",
    ""]
for county in OFFICIAL_COUNTY_NAMES:
    county_mps = mps_by_county.get(county, [])
    var_name = county.upper().replace("'","").replace(" ","_").replace("-","_") + "_MPS"
    code = COUNTY_CODES[county]
    lines.append(f"export const {var_name}: ParliamentMP[] = [")
    for mp in county_mps:
        def ts(s): return "'" + s.replace("\\","\\\\").replace("'","\\'") + "'" if s else "''"
        full_name = "Hon. " + mp['name']
        official_title = "MP, " + mp['constituency']
        lines.append(f"  {{ id: {ts(mp['id'])}, fullName: {ts(full_name)}, officialTitle: {ts(official_title)}, party: {ts(mp['party'])}, coalition: {ts(mp['coalition'])}, jurisdiction: {ts(mp['constituency'])}, countyName: {ts(county)}, countyCode: {code}, status: {ts(mp['status'])}, profileUrl: {ts(mp['profile_url'])}, rawName: {ts(mp['raw_name'])}, source: 'Parliament of Kenya (parliament.go.ke)' }},")
    lines.append("];")
lines.append("")
lines.append("export function getParliamentMPsForCounty(countyName: string): ParliamentMP[] {")
lines.append("  switch (countyName) {")
for county in OFFICIAL_COUNTY_NAMES:
    var_name = county.upper().replace("'","").replace(" ","_").replace("-","_") + "_MPS"
    lines.append(f'    case "{county}": return {var_name};')
lines.append('    default: return [];')
lines.append("  }")
lines.append("}")
lines.append(f"export const PARLIAMENT_MPS_TOTAL = {sum(len(v) for v in mps_by_county.values())};")

OUTPUT.parent.mkdir(parents=True, exist_ok=True)
OUTPUT.write_text("\n".join(lines))
print(f"✓ Wrote {OUTPUT} — {sum(len(v) for v in mps_by_county.values())} MPs across {len(mps_by_county)} counties")
